apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: oci-la-credentials-secret
  namespace: kube-system
stringData:
  config: |-
    [DEFAULT]
    user=<user ocid>
    fingerprint=<fingerprint>
    key_file=<key file path>
    tenancy=<tenancy ocid>
    region=<region>
  private.pem: |-
    -----BEGIN RSA PRIVATE KEY-----
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    -----END RSA PRIVATE KEY-----